import type { Locale } from "./i18n/config";

/* Тексты «Бонус за рекомендацию» — профиль, кабинет, баннер для друга. */
export const REF_TEXT = {
  ru: {
    badge: "Бонус",
    title: "🎁 Бонус за рекомендацию",
    friendGets: "Другу:",
    youGet: "Вам:",
    left: (n: number) => `Осталось бонусов: ${n}`,
    recommend: "Порекомендовать другу",
    yourName: "Ваше имя — его увидит друг и специалист",
    namePh: "Например: Ольга",
    getCode: "Получить код для друга",
    codeIs: "Ваш код для друга:",
    send: "Отправьте другу эту ссылку:",
    copy: "Скопировать",
    copied: "✓ Скопировано",
    shareTg: "Отправить в Telegram",
    shareWa: "Отправить в WhatsApp",
    shareText: (master: string, friend: string, code: string) => `Рекомендую специалиста: ${master}. По моему коду ${code} — ${friend}`,
    disclaimer: "Бонус даёт сам специалист. NomerOk не участвует в расчётах.",
    ended: "Бонусы у этого специалиста закончились.",
    error: "Не получилось — попробуйте ещё раз.",
    bannerTitle: (name: string) => `Вас рекомендует ${name} 🎁`,
    bannerText: (code: string, friend: string) => `Назовите специалисту код ${code} — ${friend}`,
    msgNote: (code: string) => `Код рекомендации ${code} добавим к сообщению автоматически.`,
    msgLine: (code: string, name: string) => `🎁 Код рекомендации: ${code} (рекомендовал(а) ${name})`,
    // кабинет
    cabTitle: "🎁 Бонус за рекомендацию",
    cabHint: "Клиенты рекомендуют вас друзьям и получают личный код. Друг называет код — вы даёте бонус. Условия придумываете вы, выполняете тоже вы.",
    on: "Включить бонус",
    friendLabel: "Что получит новый клиент (друг)",
    friendPh: "Например: скидка 10% на первый визит",
    rewardLabel: "Что получит тот, кто порекомендовал",
    rewardPh: "Например: −10% на следующий визит",
    optional: "(необязательно)",
    limitLabel: "Сколько бонусов готовы выдать",
    noLimit: "Без ограничения",
    prefixLabel: "Начало кода",
    prefixHint: (ex: string) => `Каждый рекомендатель получит свой код, например ${ex}. Так вы видите, кто кого привёл.`,
    save: "Сохранить",
    saved: "✓ Сохранено",
    restart: "Начать счёт заново",
    issued: (n: number, max: number) => (max ? `Выдано кодов: ${n} из ${max}` : `Выдано кодов: ${n}`),
    codes: "Последние коды",
    noCodes: "Пока никто не брал код.",
    from: "от",
  },
  en: {
    badge: "Bonus",
    title: "🎁 Referral bonus",
    friendGets: "Your friend gets:",
    youGet: "You get:",
    left: (n: number) => `Bonuses left: ${n}`,
    recommend: "Recommend to a friend",
    yourName: "Your name — your friend and the specialist will see it",
    namePh: "E.g.: Olga",
    getCode: "Get a code for my friend",
    codeIs: "Your code for a friend:",
    send: "Send your friend this link:",
    copy: "Copy",
    copied: "✓ Copied",
    shareTg: "Send via Telegram",
    shareWa: "Send via WhatsApp",
    shareText: (master: string, friend: string, code: string) => `I recommend this specialist: ${master}. With my code ${code} you get: ${friend}`,
    disclaimer: "The bonus is given by the specialist. NomerOk takes no part in payments.",
    ended: "This specialist has run out of bonuses.",
    error: "Something went wrong — please try again.",
    bannerTitle: (name: string) => `${name} recommends this specialist 🎁`,
    bannerText: (code: string, friend: string) => `Tell the specialist the code ${code} — ${friend}`,
    msgNote: (code: string) => `We'll add referral code ${code} to your message.`,
    msgLine: (code: string, name: string) => `🎁 Referral code: ${code} (recommended by ${name})`,
    cabTitle: "🎁 Referral bonus",
    cabHint: "Clients recommend you to friends and get a personal code. The friend tells you the code — you give the bonus. You set the terms and honour them yourself.",
    on: "Turn on the bonus",
    friendLabel: "What the new client (friend) gets",
    friendPh: "E.g.: 10% off the first visit",
    rewardLabel: "What the person who recommended gets",
    rewardPh: "E.g.: 10% off the next visit",
    optional: "(optional)",
    limitLabel: "How many bonuses you're ready to give",
    noLimit: "No limit",
    prefixLabel: "Code prefix",
    prefixHint: (ex: string) => `Each recommender gets their own code, e.g. ${ex}. You'll see who referred whom.`,
    save: "Save",
    saved: "✓ Saved",
    restart: "Restart the count",
    issued: (n: number, max: number) => (max ? `Codes issued: ${n} of ${max}` : `Codes issued: ${n}`),
    codes: "Latest codes",
    noCodes: "No one has taken a code yet.",
    from: "from",
  },
  ka: {
    badge: "ბონუსი",
    title: "🎁 ბონუსი რეკომენდაციისთვის",
    friendGets: "მეგობარს:",
    youGet: "თქვენ:",
    left: (n: number) => `დარჩენილი ბონუსები: ${n}`,
    recommend: "მეგობარს ურჩიეთ",
    yourName: "თქვენი სახელი — ნახავს მეგობარი და სპეციალისტი",
    namePh: "მაგ.: ოლღა",
    getCode: "კოდის მიღება მეგობრისთვის",
    codeIs: "თქვენი კოდი მეგობრისთვის:",
    send: "გაუგზავნეთ მეგობარს ეს ბმული:",
    copy: "კოპირება",
    copied: "✓ დაკოპირდა",
    shareTg: "Telegram-ით გაგზავნა",
    shareWa: "WhatsApp-ით გაგზავნა",
    shareText: (master: string, friend: string, code: string) => `გირჩევთ სპეციალისტს: ${master}. ჩემი კოდით ${code} — ${friend}`,
    disclaimer: "ბონუსს თავად სპეციალისტი იძლევა. NomerOk ანგარიშსწორებაში არ მონაწილეობს.",
    ended: "ამ სპეციალისტს ბონუსები ამოეწურა.",
    error: "ვერ მოხერხდა — სცადეთ ხელახლა.",
    bannerTitle: (name: string) => `${name} გირჩევთ ამ სპეციალისტს 🎁`,
    bannerText: (code: string, friend: string) => `უთხარით სპეციალისტს კოდი ${code} — ${friend}`,
    msgNote: (code: string) => `რეკომენდაციის კოდს ${code} შეტყობინებას ავტომატურად დავამატებთ.`,
    msgLine: (code: string, name: string) => `🎁 რეკომენდაციის კოდი: ${code} (ურჩია ${name})`,
    cabTitle: "🎁 ბონუსი რეკომენდაციისთვის",
    cabHint: "კლიენტები გირჩევენ მეგობრებს და იღებენ პირად კოდს. მეგობარი გეუბნებათ კოდს — თქვენ აძლევთ ბონუსს. პირობებს თქვენ ადგენთ და ასრულებთ.",
    on: "ბონუსის ჩართვა",
    friendLabel: "რას მიიღებს ახალი კლიენტი (მეგობარი)",
    friendPh: "მაგ.: 10% ფასდაკლება პირველ ვიზიტზე",
    rewardLabel: "რას მიიღებს ის, ვინც გირჩიათ",
    rewardPh: "მაგ.: −10% შემდეგ ვიზიტზე",
    optional: "(არასავალდებულო)",
    limitLabel: "რამდენი ბონუსის გაცემა შეგიძლიათ",
    noLimit: "შეზღუდვის გარეშე",
    prefixLabel: "კოდის დასაწყისი",
    prefixHint: (ex: string) => `ყველა რეკომენდატორი თავის კოდს მიიღებს, მაგ. ${ex}.`,
    save: "შენახვა",
    saved: "✓ შენახულია",
    restart: "დათვლის თავიდან დაწყება",
    issued: (n: number, max: number) => (max ? `გაცემული კოდები: ${n} / ${max}` : `გაცემული კოდები: ${n}`),
    codes: "ბოლო კოდები",
    noCodes: "კოდი ჯერ არავის აუღია.",
    from: "—",
  },
} satisfies Record<Locale, unknown>;
